-- Platform administration is capability-driven. Human owners never receive service-role bypass.
create type public.platform_admin_status as enum ('invited','active','suspended','revoked');
create type public.platform_invitation_status as enum ('pending','accepted','expired','revoked');

create table public.platform_roles(id uuid primary key default gen_random_uuid(),role_key text not null unique,display_name text not null,description text,is_system boolean not null default false,is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.platform_role_capabilities(id uuid primary key default gen_random_uuid(),role_id uuid not null references public.platform_roles(id) on delete cascade,capability text not null check(capability like 'platform.%' and capability=lower(capability)),created_at timestamptz not null default now(),unique(role_id,capability));
create table public.platform_admin_memberships(id uuid primary key default gen_random_uuid(),account_id uuid not null references public.accounts(id) on delete restrict,role_id uuid not null references public.platform_roles(id) on delete restrict,status public.platform_admin_status not null default 'active',granted_by_account_id uuid references public.accounts(id) on delete restrict,granted_at timestamptz not null default now(),revoked_by_account_id uuid references public.accounts(id) on delete restrict,revoked_at timestamptz,reason text,unique(account_id,role_id));
create table public.platform_admin_capability_grants(id uuid primary key default gen_random_uuid(),account_id uuid not null references public.accounts(id) on delete restrict,capability text not null check(capability like 'platform.%' and capability=lower(capability)),effect text not null check(effect in ('allow','deny')),granted_by_account_id uuid references public.accounts(id) on delete restrict,reason text,granted_at timestamptz not null default now(),revoked_at timestamptz);
create unique index platform_admin_capability_grants_active_ux on public.platform_admin_capability_grants(account_id,capability) where revoked_at is null;
create table public.platform_ownership(singleton boolean primary key default true check(singleton),owner_account_id uuid not null unique references public.accounts(id) on delete restrict,established_at timestamptz not null default now(),transferred_at timestamptz,previous_owner_account_id uuid references public.accounts(id) on delete restrict,transfer_reason text);
create table public.platform_admin_invitations(id uuid primary key default gen_random_uuid(),email_normalized text not null,role_id uuid not null references public.platform_roles(id) on delete restrict,token_hash text not null unique,status public.platform_invitation_status not null default 'pending',invited_by_account_id uuid not null references public.accounts(id) on delete restrict,expires_at timestamptz not null,accepted_by_account_id uuid references public.accounts(id) on delete restrict,accepted_at timestamptz,revoked_at timestamptz,created_at timestamptz not null default now(),check(email_normalized=lower(btrim(email_normalized))));
create index platform_admin_invitations_email_idx on public.platform_admin_invitations(email_normalized,status);
create table public.admin_step_up_sessions(id uuid primary key default gen_random_uuid(),account_id uuid not null references public.accounts(id) on delete cascade,auth_session_id uuid,assurance_level text not null check(assurance_level in ('aal2','recovery_verified')),verified_at timestamptz not null default now(),expires_at timestamptz not null,created_at timestamptz not null default now());
create index admin_step_up_sessions_account_expiry_idx on public.admin_step_up_sessions(account_id,expires_at desc);

insert into public.platform_roles(role_key,display_name,description,is_system) values
('super_admin','Super Admin','Broad platform administration. Ownership transfer remains owner-only.',true),('trust_admin','Trust & Safety','Provider verification, moderation and safety operations.',true),('finance_admin','Finance','Payments, refunds, payouts, reconciliation and disputes.',true),('discovery_admin','Discovery & SEO','Taxonomy, public pages, indexability and discovery controls.',true),('operations_admin','Operations','Operational monitoring, incidents and controlled feature operations.',true),('support_admin','Support','Support diagnostics and limited intervention.',true),('auditor','Auditor','Read-only audit and compliance access.',true);

with caps(role_key,capability) as (values
('super_admin','platform.admin.manage'),('super_admin','platform.admin.view_audit'),('super_admin','platform.markets.read'),('super_admin','platform.markets.manage'),('super_admin','platform.taxonomy.read'),('super_admin','platform.taxonomy.manage'),('super_admin','platform.seo.read'),('super_admin','platform.seo.manage'),('super_admin','platform.trust.read'),('super_admin','platform.trust.verify'),('super_admin','platform.trust.moderate'),('super_admin','platform.projects.read'),('super_admin','platform.projects.intervene'),('super_admin','platform.money.read'),('super_admin','platform.money.refund'),('super_admin','platform.money.payout'),('super_admin','platform.money.reconcile'),('super_admin','platform.money.dispute_manage'),('super_admin','platform.operations.read'),('super_admin','platform.operations.feature_flags'),('super_admin','platform.support.read'),('super_admin','platform.support.intervene'),
('trust_admin','platform.trust.read'),('trust_admin','platform.trust.verify'),('trust_admin','platform.trust.moderate'),('trust_admin','platform.admin.view_audit'),
('finance_admin','platform.money.read'),('finance_admin','platform.money.refund'),('finance_admin','platform.money.payout'),('finance_admin','platform.money.reconcile'),('finance_admin','platform.money.dispute_manage'),('finance_admin','platform.admin.view_audit'),
('discovery_admin','platform.taxonomy.read'),('discovery_admin','platform.taxonomy.manage'),('discovery_admin','platform.seo.read'),('discovery_admin','platform.seo.manage'),('discovery_admin','platform.markets.read'),('discovery_admin','platform.admin.view_audit'),
('operations_admin','platform.operations.read'),('operations_admin','platform.operations.feature_flags'),('operations_admin','platform.projects.read'),('operations_admin','platform.admin.view_audit'),
('support_admin','platform.support.read'),('support_admin','platform.support.intervene'),('support_admin','platform.projects.read'),
('auditor','platform.admin.view_audit'),('auditor','platform.money.read'),('auditor','platform.trust.read'),('auditor','platform.projects.read'),('auditor','platform.seo.read'))
insert into public.platform_role_capabilities(role_id,capability) select r.id,c.capability from caps c join public.platform_roles r on r.role_key=c.role_key;

create or replace function app_private.current_account_is_owner() returns boolean language sql stable security definer set search_path=public,app_private as $$select exists(select 1 from public.platform_ownership o join public.accounts a on a.id=o.owner_account_id where a.auth_user_id=auth.uid() and a.status='active')$$;
create or replace function app_private.current_account_has_platform_capability(p_capability text) returns boolean language sql stable security definer set search_path=public,app_private as $$with me as(select id from public.accounts where auth_user_id=auth.uid() and status='active'),deny as(select 1 from public.platform_admin_capability_grants g join me on me.id=g.account_id where g.capability=p_capability and g.effect='deny' and g.revoked_at is null),allow_direct as(select 1 from public.platform_admin_capability_grants g join me on me.id=g.account_id where g.capability=p_capability and g.effect='allow' and g.revoked_at is null),allow_role as(select 1 from public.platform_admin_memberships m join me on me.id=m.account_id join public.platform_role_capabilities rc on rc.role_id=m.role_id where m.status='active' and m.revoked_at is null and rc.capability=p_capability) select app_private.current_account_is_owner() or(not exists(select 1 from deny) and(exists(select 1 from allow_direct) or exists(select 1 from allow_role)))$$;
create or replace function app_private.current_account_has_capability(p_capability text) returns boolean language sql stable security definer set search_path=public,app_private as $$select case when p_capability like 'platform.%' then app_private.current_account_has_platform_capability(p_capability) else exists(select 1 from public.account_capabilities ac join public.accounts a on a.id=ac.account_id where a.auth_user_id=auth.uid() and a.status='active' and ac.capability=p_capability and ac.revoked_at is null) end$$;
create or replace function app_private.current_auth_is_aal2() returns boolean language sql stable as $$select coalesce(auth.jwt()->>'aal','aal1')='aal2'$$;

create or replace function public.bootstrap_platform_owner_command(p_account_id uuid,p_reason text) returns void language plpgsql security invoker set search_path=public,app_private as $$begin if auth.role()<>'service_role' then raise exception 'service role required' using errcode='42501'; end if; if exists(select 1 from public.platform_ownership) then raise exception 'platform owner already established'; end if; if not exists(select 1 from public.accounts where id=p_account_id and status='active') then raise exception 'active account required'; end if; insert into public.platform_ownership(singleton,owner_account_id,transfer_reason) values(true,p_account_id,nullif(btrim(p_reason),'')); insert into public.audit_events(actor_type,action,resource_type,resource_id,reason_code,data_classification,metadata) values('system','PLATFORM_OWNER_ESTABLISHED','account',p_account_id,'initial_bootstrap','system_internal',jsonb_build_object('reason',p_reason)); end$$;
revoke all on function public.bootstrap_platform_owner_command(uuid,text) from public,anon,authenticated; grant execute on function public.bootstrap_platform_owner_command(uuid,text) to service_role;

create or replace function public.grant_platform_role_command(p_account_id uuid,p_role_key text,p_reason text) returns void language plpgsql security invoker set search_path=public,app_private as $$declare me uuid; rid uuid; begin select id into me from public.accounts where auth_user_id=auth.uid() and status='active'; if me is null or not app_private.current_account_has_platform_capability('platform.admin.manage') then raise exception 'not authorized'; end if; if not app_private.current_auth_is_aal2() and not app_private.current_account_is_owner() then raise exception 'step-up authentication required'; end if; select id into rid from public.platform_roles where role_key=p_role_key and is_active; if rid is null then raise exception 'role not found'; end if; if p_role_key='super_admin' and not app_private.current_account_is_owner() then raise exception 'only platform owner may grant super admin'; end if; insert into public.platform_admin_memberships(account_id,role_id,status,granted_by_account_id,reason) values(p_account_id,rid,'active',me,nullif(btrim(p_reason),'')) on conflict(account_id,role_id) do update set status='active',granted_by_account_id=excluded.granted_by_account_id,granted_at=now(),revoked_by_account_id=null,revoked_at=null,reason=excluded.reason; insert into public.audit_events(actor_user_id,actor_type,action,resource_type,resource_id,reason_code,data_classification,metadata) values(auth.uid(),'user','PLATFORM_ROLE_GRANTED','account',p_account_id,'admin_access_change','system_internal',jsonb_build_object('role_key',p_role_key,'reason',p_reason)); end$$;
create or replace function public.revoke_platform_role_command(p_account_id uuid,p_role_key text,p_reason text) returns void language plpgsql security invoker set search_path=public,app_private as $$declare me uuid; rid uuid; begin select id into me from public.accounts where auth_user_id=auth.uid() and status='active'; if me is null or not app_private.current_account_has_platform_capability('platform.admin.manage') then raise exception 'not authorized'; end if; if p_account_id=(select owner_account_id from public.platform_ownership limit 1) then raise exception 'platform owner cannot be revoked'; end if; if p_role_key='super_admin' and not app_private.current_account_is_owner() then raise exception 'only platform owner may revoke super admin'; end if; select id into rid from public.platform_roles where role_key=p_role_key; update public.platform_admin_memberships set status='revoked',revoked_by_account_id=me,revoked_at=now(),reason=nullif(btrim(p_reason),'') where account_id=p_account_id and role_id=rid and revoked_at is null; insert into public.audit_events(actor_user_id,actor_type,action,resource_type,resource_id,reason_code,data_classification,metadata) values(auth.uid(),'user','PLATFORM_ROLE_REVOKED','account',p_account_id,'admin_access_change','system_internal',jsonb_build_object('role_key',p_role_key,'reason',p_reason)); end$$;
create or replace function public.transfer_platform_ownership_command(p_new_owner_account_id uuid,p_reason text) returns void language plpgsql security invoker set search_path=public,app_private as $$declare old_owner uuid; begin if not app_private.current_account_is_owner() then raise exception 'owner required'; end if; if not app_private.current_auth_is_aal2() then raise exception 'aal2 required'; end if; if not exists(select 1 from public.accounts where id=p_new_owner_account_id and status='active') then raise exception 'active new owner required'; end if; select owner_account_id into old_owner from public.platform_ownership where singleton=true for update; update public.platform_ownership set previous_owner_account_id=old_owner,owner_account_id=p_new_owner_account_id,transferred_at=now(),transfer_reason=nullif(btrim(p_reason),'') where singleton=true; insert into public.audit_events(actor_user_id,actor_type,action,resource_type,resource_id,reason_code,data_classification,metadata) values(auth.uid(),'user','PLATFORM_OWNERSHIP_TRANSFERRED','account',p_new_owner_account_id,'ownership_transfer','system_internal',jsonb_build_object('previous_owner_account_id',old_owner,'reason',p_reason)); end$$;
create or replace function public.admin_overview_command() returns jsonb language plpgsql security invoker set search_path=public,app_private as $$begin if not(app_private.current_account_has_platform_capability('platform.admin.manage') or app_private.current_account_has_platform_capability('platform.admin.view_audit') or app_private.current_account_has_platform_capability('platform.operations.read')) then raise exception 'not authorized'; end if; return jsonb_build_object('accounts',jsonb_build_object('active',(select count(*) from public.accounts where status='active'),'suspended',(select count(*) from public.accounts where status='suspended')),'providers',jsonb_build_object('active',(select count(*) from public.providers where status='active'),'pending_verifications',(select count(*) from public.provider_verifications where status='pending')),'work',jsonb_build_object('open_requests',(select count(*) from public.requests where state not in('completed','cancelled')),'completed',(select count(*) from public.requests where state='completed'),'disputed',(select count(*) from public.requests where state='disputed')),'money',jsonb_build_object('funded_obligations',(select count(*) from public.payment_obligations where status='funded'),'disputed_obligations',(select count(*) from public.payment_obligations where status='disputed'),'eligible_payouts',(select count(*) from public.payouts where status='eligible')),'operations',jsonb_build_object('unpublished_outbox',(select count(*) from public.outbox_events where published_at is null),'rejected_provider_events',(select count(*) from public.payment_provider_events where status='rejected'))); end$$;
grant execute on function public.grant_platform_role_command(uuid,text,text),public.revoke_platform_role_command(uuid,text,text),public.transfer_platform_ownership_command(uuid,text),public.admin_overview_command() to authenticated;

alter table public.platform_roles enable row level security; alter table public.platform_role_capabilities enable row level security; alter table public.platform_admin_memberships enable row level security; alter table public.platform_admin_capability_grants enable row level security; alter table public.platform_ownership enable row level security; alter table public.platform_admin_invitations enable row level security; alter table public.admin_step_up_sessions enable row level security;
create policy platform_roles_admin_read on public.platform_roles for select to authenticated using(app_private.current_account_has_platform_capability('platform.admin.manage'));
create policy platform_role_caps_admin_read on public.platform_role_capabilities for select to authenticated using(app_private.current_account_has_platform_capability('platform.admin.manage'));
create policy platform_memberships_admin_read on public.platform_admin_memberships for select to authenticated using(app_private.current_account_has_platform_capability('platform.admin.manage') or account_id=(select id from public.accounts where auth_user_id=auth.uid()));
create policy platform_grants_admin_read on public.platform_admin_capability_grants for select to authenticated using(app_private.current_account_has_platform_capability('platform.admin.manage') or account_id=(select id from public.accounts where auth_user_id=auth.uid()));
create policy platform_ownership_admin_read on public.platform_ownership for select to authenticated using(app_private.current_account_has_platform_capability('platform.admin.manage'));
create policy platform_invites_admin_read on public.platform_admin_invitations for select to authenticated using(app_private.current_account_has_platform_capability('platform.admin.manage'));
create policy admin_step_up_self_read on public.admin_step_up_sessions for select to authenticated using(account_id=(select id from public.accounts where auth_user_id=auth.uid()));
create policy audit_admin_read on public.audit_events for select to authenticated using(app_private.current_account_has_platform_capability('platform.admin.view_audit'));
create index platform_admin_memberships_account_status_idx on public.platform_admin_memberships(account_id,status) where revoked_at is null;
create index platform_role_capabilities_cap_idx on public.platform_role_capabilities(capability,role_id);
